SensorAPIWeb/Models/ErrorViewModel.cs
using System;

namespace SensorAPIWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SensorAPIWeb/ViewModels/DeviceCSVLoadViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorAPIWeb.ViewModels
{
    public class DeviceCSVLoadViewModel
    {
        public string SerialNumber { get; set; }

        public string Token { get; set; }
    }
}

SensorAPIWeb/ViewModels/DeviceInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorAPIWeb.ViewModels
{
    public class DeviceInfoViewModel
    {
        public string SerialNumber { get; set; }

        public string Humidity { get; set; }

        public string Temperature { get; set; }

        public DateTime UpdateTime { get; set; }
    }
}

SensorAPIWeb/ViewModels/DeviceSwitchOnViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorAPIWeb.ViewModels
{
    public class DeviceSwitchOnViewModel
    {
        public string SerialNumber { get; set; }

        public string BatteryVoltage { get; set; }

        public string FirmwareVersion { get; set; }
    }
}

SensorAPIWeb/ViewModels/DeviceUpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorAPIWeb.ViewModels
{
    public class DeviceUpdateViewModel
    {
        public string SerialNumber { get; set; }

        public string Humidity { get; set; }

        public string Temperature { get; set; }
    }
}

SensorAPIWeb/ViewModels/FileLoadResponseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorAPIWeb.ViewModels
{
    public class FileLoadResponseViewModel
    {
        public string Message { get; set; }
    }
}

SensorAPIWeb/Controllers/DeviceUpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SensorAPIWeb.Services;
using SensorAPIWeb.ViewModels;

namespace SensorAPIWeb.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DeviceUpdateController : ControllerBase
    {
        private readonly IDeviceUpdateRepository _deviceUpdateRepository;
        private readonly IGetDeviceDetailsRepository _getDeviceDetailsRepository;

        public DeviceUpdateController(IDeviceUpdateRepository deviceUpdateRepository, IGetDeviceDetailsRepository getDeviceDetailsRepository)
        {
            _deviceUpdateRepository = deviceUpdateRepository;
            _getDeviceDetailsRepository = getDeviceDetailsRepository;
        }

        // POST: api/DeviceUpdate
        [HttpPost]
        public void Post([FromBody] DeviceUpdateViewModel deviceInfo)
        {
            var result = _deviceUpdateRepository.DeviceDetailsUpdate(deviceInfo);
        }

        // PUT: api/DeviceUpdate/
        [HttpPut]
        public void Put([FromBody] DeviceSwitchOnViewModel deviceInfo)
        {
            var result = _deviceUpdateRepository.DeviceSwtichOn(deviceInfo);
        }

        // GET: api/GetDeviceInfo
        [HttpGet("{serialNumber}", Name = "GetLatestDeviceInfo")]
        public IActionResult GetLatestDeviceInfo(string serialNumber)
        {
            var result = _getDeviceDetailsRepository.GetLatestDeviceDetails(serialNumber);
            return new ObjectResult(result);
        }

    }
}

SensorAPIWeb/Controllers/DevicesDataCentreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SensorAPIWeb.Services;

namespace SensorAPIWeb.Controllers
{
    public class DevicesDataCentreController : Controller
    {
        private readonly IFileLoadRepository _fileLoadRepository;
        public DevicesDataCentreController(IFileLoadRepository fileLoadRepository)
        {
            _fileLoadRepository = fileLoadRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UploadFiles(IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                var result = _fileLoadRepository.FileLoad(file);
                return Json(result);
            }
        }
    }
}

SensorAPIWeb/Controllers/GetDeviceInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SensorAPIWeb.Services;

namespace SensorAPIWeb.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class GetDeviceInfoController : ControllerBase
    {
        private readonly IGetDeviceDetailsRepository _getDeviceDetailsRepository;

        public GetDeviceInfoController(IGetDeviceDetailsRepository getDeviceDetailsRepository)
        {
            _getDeviceDetailsRepository = getDeviceDetailsRepository;
        }

        // GET: api/DeviceUpdate
        [HttpGet("{serialNumber}", Name = "GetDeviceHistory")]
        public async Task<IActionResult> GetDeviceHistory(string serialNumber)
        {
            var result = await _getDeviceDetailsRepository.GetDeviceUpdatedHistory(serialNumber);
            return new ObjectResult(result);
        }
    }
}

SensorAPIWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SensorAPIWeb.Models;


namespace SensorAPIWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SensorAPIWeb/Views/DevicesDataCentre/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="container-full">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    API test
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            <h3>CSV File Upload</h3>
                            <div>
                                <form method="POST" action="#" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <div class="input-group input-file" name="Fichier1">
                                            <input type="text" class="form-control" placeholder='Choose a file...' />
                                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-choose pull-left" type="button">Choose</button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary " id="uploadFile">Submit</button>
                                        <button type="reset" class="btn btn-danger">Reset</button>
                                    </div>
                                </form>
                            </div>
                            <div id="messageInfo" class="alert alert-danger" role="alert" style="visibility: hidden">
                                Loading from API...
                            </div>
                            <h3>Deivce simulator  -  API Test</h3>
                            <h5>Input Token for Authentication</h5>
                            <div class="form-group">
                                <label>Token</label>
                                <div class="space5"></div>
                                <input id="token" class="form-control">
                            </div>
                            <div class="space10"></div>
                            <h3>Sensor switch on PUT request simulating</h3>
                            <div class="form-group">
                                <label>Device Serial Number</label>
                                <div class="space5"></div>
                                <input id="serialOn" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Voltage</label>
                                <div class="space5"></div>
                                <input id="voltage" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Firmware Version</label>
                                <div class="space5"></div>
                                <input id="version" class="form-control">
                            </div>
                            <div class="submitBtn">
                                <button id="deviceSwitchOn" type="submit" class="btn btn-primary">Update Device Info</button>
                            </div>
                            <div class="space10"></div>
                            <h3>Sensor Update details(Temperature,Humidity, etc...) simulating</h3>
                            <div class="form-group">
                                <label>Device Serial Number</label>
                                <div class="space5"></div>
                                <input id="serialUpdate" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Temperature</label>
                                <div class="space5"></div>
                                <input id="temperatureUpdate" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Humidity</label>
                                <div class="space5"></div>
                                <input id="humidityUpdate" class="form-control">
                            </div>
                            <div class="submitBtn">
                                <button id="deviceUpdate" type="submit" class="btn btn-primary">Update Device Details</button>
                            </div>

                        </div>
                        <div class="col-lg-5">
                            <h3>Get Device latest Details</h3>
                            <div class="form-group">
                                <label>Device Serial Number</label>
                                <div class="space5"></div>
                                <input id="serial" class="form-control">
                            </div>
                            <div class="submitBtn">
                                <button id="GetLatestDevice" type="submit" class="btn btn-primary">Get Data</button>
                            </div>
                            <h3>Device Latest Details</h3>
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <th scope="row" class="col-sm-4">Serial Number</th>
                                        <td id="serialbumber"></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Temperature</th>
                                        <td id="temperature"></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Humidity</th>
                                        <td id="humidity"></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Update Time</th>
                                        <td id="updatetime"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <h3>Get Device updated history</h3>
                            <div class="form-group">
                                <label>Device Serial Number</label>
                                <div class="space5"></div>
                                <input id="serialNB" class="form-control">
                            </div>
                            <div class="submitBtn">
                                <button id="GetHistory" type="submit" class="btn btn-primary">Get History</button>
                            </div>
                            <h3>Return Device details in Json</h3>
                            <pre id="returnData" style="height: 400px;"></pre>

                        </div>
                            <!-- /.panel-body -->
                        </div>
                    <!-- /.panel -->
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
</div>

SensorAPIWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body id="bgcontent">
    <div id="containerjambo" class="jumbotron">
        <p class="text-uppercase text-white">LX Group -  Neil NIU</p>
        <h1 class="text-uppercase text-white">API - Sensor Management</h1>
        <div class="space10"></div>
        @Html.ActionLink("Start", "Index", "DevicesDataCentre", null, new { @class = "primary-btn banner-btn" })

    </div>
    
</body>

SensorAPIWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sensor API</title>

    <environment>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/Site.css" />
        <link rel="stylesheet" href="~/css/homepage.css" />
        <link rel="stylesheet" href="~/css/table.css" />
    </environment>

</head>
<body id="bgcontent">
    @*<header class="header">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo">
                                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sensor API Management</a>
                            </div>

                            <div class="phone_num ml-auto">
                                <div class="phone_num_inner">
                                    <img src="images/phone.png" alt=""><span>0061 412 85 4532</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>*@
    <div id="mainnavabar" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-full">
            <div class="navbar-header page-scroll">
                @Html.ActionLink("Sensor API Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Search Settings", "Index", "Search")</li>*@
                    @*<li><a id="registerInvoke" href="#">Register</a></li>*@
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <header>
        <div id="editview" class="container-full">
            @RenderBody()
        </div>
    </header>
    <partial name="_CookieConsentPartial" />



    <environment>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>